import { useSession, signIn } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Header from "~/components/Header";

export default function Home() {
  const { data: sessionData } = useSession();
  return (
    <main>
      <Head>
        <title>Master_CP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="hero min-h-screen bg-base-200">
          <div className="hero-content text-center">
            <div className="max-w-md">
              <h1 className="text-5xl font-bold">Welcome</h1>
              <p className="py-6">
                {
                  "Master_CP is more than just an app; it's your companion on the path to programming greatness. With support for a wide range of programming languages, you have the freedom to code in your preferred language."
                }
              </p>
              <div className="flex justify-center gap-2">
                <Link className="btn btn-primary" href={"/problem-list"}>
                  {"Get Started"}
                </Link>
                {!sessionData?.user && (
                  <button
                    className="btn btn-primary"
                    onClick={() => void signIn()}
                  >
                    Sign In
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      </main>
    </main>
  );
}
